[tool.poetry]
name = "esphome-env"
version = "0.1.0"
description = ""
authors = []
readme = ""

[tool.poetry.dependencies]
python = "^3.11"
esphome = "^2023.11.6"
platformio = "^6.1.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
