substitutions:
  git_rev: undefined

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  power_save_mode: none

  # ap:
  #   ssid: ${friendly_name} Fallback AP
  #   password: !secret wifi_ap_password

# captive_portal:

# AP and/or Captive portal causes random reboots on this board :(
# See: https://github.com/esphome/issues/issues/1679
#      https://community.home-assistant.io/t/cant-stop-esphome-restarting-with-weak-wifi/453821/21

ota:
  safe_mode: true
  port: 3232
  password: !secret ota_password

debug:
  update_interval: 5s

button:
  - platform: safe_mode
    name: "Restart in Safe Mode"
    icon: "mdi:restart-alert"

  - platform: restart
    name: "Restart"
    icon: "mdi:restart"

sensor:
  - platform: debug
    free:
      name: "Heap Free"
    loop_time:
      name: "Loop Time"

  - platform: uptime
    update_interval: 5s
    name: Uptime Sensor

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 10s

text_sensor:
  - platform: debug
    reset_reason:
      name: "Reset Reason"

  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true

  - platform: template
    name: "Git Hash"
    icon: "mdi:git"
    entity_category: "diagnostic"
    lambda: |-
      return {"${git_rev}"};
