#Expected ${led} to substitute for LED number
#Expected ${pin} to substitute for the gpio pin
sensor:
- platform: duty_cycle
  name: "LED${led}"
  id: led_${led}_sensor
  update_interval: 1s
  internal: true
  pin:
    number: ${pin}
    mode:
      input: true
      pulldown: true